spring.application.name=user-service-api
server.port=8081

spring.devtools.restart.enabled=false
eureka.client.serviceUrl.defaultZone=http://127.0.0.1:8761/eureka

spring.servlet.context-path=/api/v1

spring.datasource.url=jdbc:postresql://localhost:5432/user_service_db
spring.datasource.username=smartdine
spring.datasource.password=Smart@123456
spring.datasource.drive-class-name=org.postgresql.Driver
spring.datasource.hikari-pool-size=10

